language: objective-c
osx_image: xcode7.3

before_install:
  - brew update
  - brew install carthage
  - carthage bootstrap

script:
  - ./scripts/test-coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)