language: objective-c
osx_image: xcode7.3

before_install:
  - carthage bootstrap

install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - ./scripts/test-coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)